version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps-1.10.1.536
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4c:49:12:b3:5f:94:d0:0c:ae:62:3e:d8:67:6b:15:d2"

      - checkout

      - setup_remote_docker

      - run:
          name: Build docker image
          command: make image

      - run:
          name: Tag git repo
          command: make git-tag

      - run:
          name: Push docker image to docker hub
          command: |
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              make release

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
